# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94e37111112f55e8b4ed0437b21700f5cd117c8bc42410e5abf7a318142e4dd29d9b66caca6eb93aec0377ef942c032c9bbe30d0956d1b8b42b7351e9d54b143

test:
  secret_key_base: 377f2d2f65b078593ac1ddbcfed663b0d052d1c7f53374c7effde6ec53ec94e312f5711c137c70d80bdbf9cccab710f4be3dc7921b86c42ccb746b018471b9a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
