# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa4d43ccf47c25ce4183c17d826a6497388f6ad24b099c3345ef646a7f1c42d8023eec23b18d0d19cfbabf29ac34f536634e7bef40d7a09388c27212b7b93bec

test:
  secret_key_base: 5bfa852992c2cf1217aad2ff2c6b965f0c700c1cf5723871e5f9b284a9269dd494cf48bb0b342cf7cdd4f745df34e832081ecc3a49ea92d3133e451da5df55fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
